### ISSUE TITLE
How can I generate model.tflite file after training

### ISSUE THREAD

**Issue by namhong1412** [JanPalasek/ulozto-captcha-breaker#14]
I have trained and have a lot of .f5 files, I can't convert them to tflite, how can I use bin/create_tflite.py?

**Comment by JanPalasek** [comment]
I remember only that the weights file had extension .h5.

You need to load the weights and then save them into a model using st like `tf.keras.save_model` function. This, you can feed into into `bin/create_tflite.py` script.

But I would recommend, for this purpose, to read the tensorflow documentation on this issue and use its methods directly. I haven't worked in tensorflow properly for a few years.
